config/routes.rb
ContainerConsole::Application.routes.draw do
  root :to => 'containers#index'

  resources :containers do
    member do
      get 'start'
      get 'stop'
    end
  end
      

end

app/models/container.rb
class Container
  extend ActiveModel::Naming

  def initialize(container = nil)
    if container.kind_of? Hash
      @params = container
    else
      @params = {
        :name => container.try(:name),
        :template => "ubuntu"
      }
      @container = container
    end
  end

  def template
    @params[:template]
  end

  def name
    @params[:name]
  end

  def execute(*args)
    @container.execute(*args)
  end

  def state
    @container.try(:state)
  end
  
  def start
    @container.start("-d")
  end

  def stop
    @container.stop
  end

  def save
    if persisted?
      false
    else
      CreateContainerWorker.perform_async(name, "-t #{template}")
    end
  end

  def persisted?
    @container != nil
  end

  def to_key
    [name] if name
  end

  def destroy
    @container.destroy
  end

  def to_partial_path
    "container"
  end

  def to_s
    name
  end

  def self.find(name)
    all.find {|c| c.name == name}
  end

  def self.all
    LXC.new.containers.collect do |container|
      new(container)
    end
  end
end

app/models/container_template.rb
class ContainerTemplate
  def initialize(fullname)
    @fullname = fullname
  end

  def name
    @fullname[4..-1]
  end

  def self.all
    [].tap do |list|
      Dir.new("/usr/lib/lxc/templates").entries.each do |entry|
        list << new(entry) unless entry[0] == "."
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_filter :set_container, only: [:show, :start, :stop, :destroy]

  def index
    @containers = Container.all
  end

  def new
    @container = Container.new
  end

  def show
    @things = @container.execute("/bin/true")
  end

  def start
    @container.start
    redirect_to @container
  end

  def stop
    @container.stop
    redirect_to @container
  end

  def create
    @container = Container.new(params[:container])
    if @container.save
      redirect_to containers_path
    else
      render 'new'
    end
  end

  def destroy
    @container.destroy
    redirect_to containers_path
  end

  private

    def set_container
      @container = Container.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_button(name, path)
    link_to name, path, class: 'btn btn-default'
  end

  def primary_button(name, path)
    link_to name, path, class: 'btn btn-primary'
  end

  def danger_button(name, path, options = {})
    link_to name, path, {class: 'btn btn-danger'}.merge(options)
  end

  def success_label(caption)
    content_tag(:span, caption, class: 'label label-success')
  end

  def danger_label(caption)
    content_tag(:span, caption, class: 'label label-danger')
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
  def stop_start_button(container)
    if container.state == :stopped
      primary_button("Start", start_container_path(container))
    else
      danger_button("Stop", stop_container_path(container))
    end
  end

  def state_badge(container)
    if container.state == :stopped
      danger_label(:stopped)
    elsif container.state == :running
      success_label(:running)
    end
  end
end

app/views/containers/_container.html.erb
<tr>
  <td><%= link_to container, container %></td>
  <td><%= state_badge(container) %></td>
  <td>
    <%= stop_start_button(container) %>
    <%= danger_button "Delete", container_path(container), method: :delete %>
  </td>
</tr>

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :template %>
    <%= f.select :template, ContainerTemplate.all.collect(&:name), {}, { class: 'form-control' } %>
  </div>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= default_button "Cancel", containers_path %>
<% end %>

app/views/containers/index.html.erb
<h1>Containers</h1>

<%= primary_button "New Container", new_container_path %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <%= render @containers %>
  </tbody>
</table>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form' %>

app/views/containers/show.html.erb
<h1><%= @container.name %></h1>

<code><%= @things %></code>

<p>
  <%= default_button("Back", containers_path) %>
  <%= stop_start_button(@container) %>
</p>

<p>
  State: <b><%= @container.state %></b>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Container Console</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>